### ISSUE TITLE
Create HTML email template for when recipent recieves certificate.

### ISSUE THREAD

**Issue by GautamPatil1** [GautamPatil1/credify-server#5]

**Comment by shrinivas9606** [comment]
<body style="margin: 0; padding: 0; font-family: Arial, sans-serif; line-height: 1.6; background-color: #f4f4f4;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
        <tr>
            <td style="padding: 20px 0;">
                <table role="presentation" width="600px" align="center" cellspacing="0" cellpadding="0" border="0" style="max-width: 600px; margin: auto; padding: 20px; background-color: #ffffff; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
                    <tr>
                        <td align="center">
                            <h1 style="color: #333;">Congratulations on Receiving Your Certificate!</h1>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p style="color: #555;">Dear [Recipient's Name],</p>
                            <p style="color: #555;">Congratulations! You have successfully completed the requirements for [Certificate Name]. We are pleased to present you with this certificate as recognition of your achievement.</p>
                            <p style="color: #555;">We hope this certificate serves as a testament to your dedication and hard work. Keep up the excellent work!</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p style="color: #555;">Sincerely,</p>
                            <p style="color: #555;">The [Your Organization] Team</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
